### ISSUE TITLE
"response.slice is not a function" when ledger is not connected

### ISSUE THREAD

**Issue by fedekunze** [ZondaX/ledger-cosmos-js#10]
if the Ledger is not connected, the library throws the following error after timeout (in the case of `get_version`)

```
TypeError: response.slice is not a function
    at ledger-app.js:123
    at _rejected (q.js:864)
    at q.js:890
    at Promise.when (q.js:1142)
    at Promise.promise.promiseDispatch (q.js:808)
    at q.js:624
    at runSingle (q.js:137)
    at flush (q.js:125)
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
```

**Comment by jleni** [comment]
Thanks! I will have a look today

**Comment by jleni** [comment]
@fedekunze Now it should be also possible to detect three conditions:

1) App loaded
2) No app
3) no device

by polling get_version

![image 1](https://user-images.githubusercontent.com/13698520/52954086-79e38200-3389-11e9-9d82-e9cf22d28946.png)
