### ISSUE TITLE
Error mismatch between get_version and publicKey

### ISSUE THREAD

**Issue by fedekunze** [ZondaX/ledger-cosmos-js#12]
Bug steps:

1. Connect ledger and wait until the screen shows the message `vires in numeris...`
2. Call `get_version()` => `error_message = No errors`
3. Call `publicKey(HDPATH)` => `error_message = Unknown error code`

**Comment by jleni** [comment]
@fedekunze Do we still need changes here after our chat?

**Comment by fedekunze** [comment]
No, this can be handled client side. I created an issue on voyager for it https://github.com/cosmos/voyager/issues/2015
