### ISSUE TITLE
It can be running in browser without nodejs?

### ISSUE THREAD

**Issue by yulidai** [ZondaX/ledger-cosmos-js#16]
I hope can use ledger in browser for users

when using `https://github.com/LedgerHQ/ledgerjs`, i find it's ok for BTC or ETH, but failed in COSMOS.

so this one can just running in browser or not? 

Thanks   :)

**Comment by jleni** [comment]
There is support for both node.js and U2F.

The browser tests are here:

https://github.com/ZondaX/ledger-cosmos-js/blob/8197d8f196c6e41a6e4038cb245f234543314aa7/package.json#L34-L35

You will need to set up a webserver with HTTPS support for testing purposes.
There is a Caddy configuration here that should work well:

https://github.com/ZondaX/ledger-cosmos-js/tree/master/tests/browser

**Comment by jleni** [comment]
By the way, Voyager (https://github.com/cosmos/voyager) uses this library for webwallet / browser support.

**Comment by yulidai** [comment]
thanks, i'll try it later  👍

**Comment by jleni** [comment]
Just run Caddy in `tests/browser`
npm browserify and browserify-test should place the files in there

**Comment by yulidai** [comment]
when i include `ledger.js` and `chrome-u2f-api.js` into my react(web) project, a lot of error occured. seems need RequireJS? but it not found at your project.

i'll try to fix it, and would appreciate it if you could improve the documentation  :P

**Comment by yulidai** [comment]
i'm successed by using `<script>` instead of import, like test file.
