### ISSUE TITLE
Sign Message seems should be process before using

### ISSUE THREAD

**Issue by yulidai** [ZondaX/ledger-cosmos-js#17]
it works after deleting a little bytes（in tests/test-browser.js), but when using `gaiacli` seems no problem
```
    return comm.create_async(TIMEOUT, true).then(
        function (comm) {
        try {
            let dev = new ledger.App(comm);

            dev.get_version().then(function (result) {
                console.log(result);
            })
                
            let path = [44, 118, 0, 0, 0];
            dev.sign(path, '{"account_number":"4","chain_id":"testing","fee":{"amount":[{"amount":"2","denom":"ether"}],"gas":"150000"},"memo":"","msgs":[{"type":"cosmos-sdk/MsgDelegate","value":{"delegator_address":"cosmos1ecpxal85dwrs5hsfa5x8ezxu6mey5e05mcw08m","validator_address":"cosmosvaloper157rlp7xv7ee76f5mdh8hzvhg9arxvms9u0q27k","value":{"amount":"100","denom":"stake"}}}],"sequence":"10"}').then(function(res) {
                let sig = res.signature.slice(-66);
                console.log(sig.length)

                result = Buffer.from(`${sig.slice(0, 32).toString('hex')}${sig.slice(34).toString('hex')}`, 'hex');
                console.log(result.toString('base64'))
                console.log(result.toString('hex'))
                console.log(result.length)
            })                
        }
        catch (e) {
            console.log(e)
        }
    });
```

**Comment by yulidai** [comment]
Any ideas about it? Thank you

**Comment by jleni** [comment]
I am not sure what you mean in the title.
What you are showing it is not actually a bug. The device returns DER signatures and your are probably looking for BER signatures.

**Comment by yulidai** [comment]
Thanks, i'll learn how to convert the DER msg(`res.signature`) to BER signatures

**Comment by webmaster128** [comment]
Cosmos requires transactions to be in fixed length encoding (32 bytes `r`, 32 bytes `s`). The DER encoding returned by Ledger contains the two integers `r` and `s` in variable length.

You find a DER decoder and fixed length encoder in CosmJS

- `Secp256k1Signature.fromDer`: https://github.com/cosmos/cosmjs/blob/v0.25.4/packages/crypto/src/secp256k1signature.ts#L33-L74
- `Secp256k1Signature.toFixedLength`: https://github.com/cosmos/cosmjs/blob/v0.25.4/packages/crypto/src/secp256k1signature.ts#L122-L124

which can be applied as follows:

```ts
Secp256k1Signature.fromDer((response as any).signature).toFixedLength()
```

(see https://github.com/cosmos/cosmjs/blob/v0.25.4/packages/ledger-amino/src/launchpadledger.ts#L98)
