### ISSUE TITLE
Pubkey isn't returned correctly 

### ISSUE THREAD

**Issue by Liamsi** [ZondaX/ledger-cosmos-js#3]
This will return the first 64 bytes of the uncompressed key (instead of the needed 65 bytes):

https://github.com/ZondaX/ledger-cosmos-js/blob/32b95aca04c3acc225c09b7b1d68cc6b25655815/src/ledger-app.js#L154
(one off bug, classic ;-D)

**Comment by fedekunze** [comment]
this should be:
`result["pk"] = Buffer.from(apduResponse.slice(0, 65));`

**Comment by Liamsi** [comment]
Hah, that makes eben more sense as the error code seems to be in the last two bytes (-2). JS, is confusing:
https://github.com/ZondaX/ledger-cosmos-js/blob/32b95aca04c3acc225c09b7b1d68cc6b25655815/src/ledger-app.js#L152-L154

**Comment by jleni** [comment]
yes, that is incorrect. Who sends the PR first? :)
