### ISSUE TITLE
Ledger: Fail to send token: Data is invalid : Unrecognized error code

### ISSUE THREAD

**Issue by lufa23** [Zondax/ledger-cosmos-js#56]
**Description:**
Several issues are witnessed for Ledger user when using Keplr wallet.
Both  Keplr and Ledger teams have been reached out, and it seems the issue is on Zondax's side

Please look at these tickets for further information:
https://github.com/cosmos/ledger-cosmos/issues/65
https://github.com/chainapsis/keplr-wallet/issues/368
https://github.com/Sifchain/Support-Tickets/issues/378

:link: [zboto Link](https://app.clickup.com/t/2tk4yn8)

**Comment by faboweb** [comment]
@marbar3778 messaged you

**Comment by intercos** [comment]
The issue of IBC token send impossible
It's definitely something to do with the Cosmos App update.
https://github.com/chainapsis/keplr-wallet/issues/368#issuecomment-1145385768

**Comment by lufa23** [comment]
hey @marbar3778 , we are not able to get the amino signed encoded message in the console. 
We tried to make some changes on our devnet, but still it seems that it's not an issue on our side.
Here's the error we have when testing ledger with the devnet changes (that we hoped would work):
<img width="346" alt="image (13)" src="https://user-images.githubusercontent.com/67415638/172609661-b6053b44-4758-400f-a766-f3b5e0be6a7f.png">

**Comment by ftheirs** [comment]
A new version was published by Ledger. It should be solved!
