### ISSUE TITLE
Support for MsgSetWithdrawAddress

### ISSUE THREAD

**Issue by vietnamese-chowder** [Zondax/ledger-cosmos-js#62]
I'm trying to sign a `MsgSetWithdrawAddress`, and correct me if I'm wrong, but it seems it's not supported currently. During signing I see `cosmos-sdk/MsgSetWithdrawAddress` as the message type and the withdraw field name is also not "prettified" as with `MsgSend` or `MsgDelegate`, and sending with it throws a signature error. Can you please support this message type?

**Comment by vietnamese-chowder** [comment]
This is the message I'm passing to sign:

```
{
  "account_number": "8",
  "chain_id": "testing",
  "fee": {
    "amount": [
      {
        "amount": "5000",
        "denom": "uatom"
      }
    ],
    "gas": "200000"
  },
  "memo": "",
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSetWithdrawAddress",
      "value": {
        "delegator_address": "cosmos1hr9x0sjvel6z3vt9qny8sdd5gnnlgk0p69d6cv",
        "withdraw_address": "cosmos12d64j98tjjpqkx70r08aspc4nvntqp2w6wr2de"
      }
    },
    {
      "type": "cosmos-sdk/MsgWithdrawDelegationReward",
      "value": {
        "delegator_address": "cosmos1hr9x0sjvel6z3vt9qny8sdd5gnnlgk0p69d6cv",
        "validator_address": "cosmosvaloper13dr26wdygna3s8fdl5tlc45m2le2ydyddxzj49"
      }
    }
  ],
  "sequence": "7"
}
```

**Comment by ftheirs** [comment]
Hi @vietnamese-chowder! Thanks for your report! We'll check it and come back with more info about this! 😄 
Ohh, btw, this issue is related to the app, not the JS package and the repositories were moved to cosmos organization. Would you mind to close this and open the issue [here](https://github.com/cosmos/ledger-cosmos)?

**Comment by vietnamese-chowder** [comment]
Oh, sure! And thanks

**Comment by vietnamese-chowder** [comment]
https://github.com/cosmos/ledger-cosmos/issues/71
